process writeFastaFromChannel{
    publishDir "$params.outFolder/seqs", mode: "copy"
    tag "${outname}"

    input:
    val seqlist
    val outname

    output:
    path "*.fasta", emit: found

    script:

    """
    cleanseq=\$( echo "$seqlist" | cut -c2- | rev | cut -c2- |rev | tr -d ' ' )
    echo "\$cleanseq" | tr ',' '\n'  > $outname
    """
}



process attendance{
    publishDir "$params.outFolder", mode: "copy"

    input:
    val collapsedSequencesCount
    val seqsInvalidCount
    val structurelessCount
    path finalMsa
    val foundSequencesCount

    script:
    """
    echo $finalMsa
    fin=\$(grep -c ">" $finalMsa)

    echo 'No. of sequences in inputfile(s): ' $foundSequencesCount >> "sequence_report.txt"

    echo 'No. of invalid sequences: ' $seqsInvalidCount >> "sequence_report.txt"
    echo 'No. of sequences not matched to a model: ' $structurelessCount >> "sequence_report.txt"
    echo 'No. of sequences matched to a model: ' $collapsedSequencesCount >> "sequence_report.txt"

    echo 'No. of sequences in final alignment: ' \$fin >> "sequence_report.txt"

    av_conservation=`python3 $projectDir/bin/shannons_entropy.py $finalMsa`
    echo 'Average sequence conservation (Shannons Entropy): ' \$av_conservation 


    if (( \$fin !=$collapsedSequencesCount + $structurelessCount ))
    then
        echo "ERROR: Not all valid sequences are found in the output file, please check $finalMsa in in the output directory!"
        exit 1
    fi

    """
}

process summary {
    publishDir "$params.outFolder", mode: "copy"

    input:
    path inputSeqFiles //allSequences
    val foundSequencesCount //allSequencesCount

    val dropSimilar
    val collapsedSequencesCount
    path similarClstr  //reducedSeqsClstr

    val seqQC
    val seqsInvalidCount
    path seqsInvalidFile

    path structuresFolder
    val foundModelsCount
    val foundModelsAF
    val foundModelsESM
    val structurelessCount
    path structurelessFile

    val createSubsets
    //val useSubsets
    path subsetClstr
    path seqsToAlignFile //foundSeqs
    path mergedMSA  //finalMsa

    val squeezePerc
    path dsspMappedMSA
    path finalMSA //squeezedMsa

    output:
    path '*.md'

    script:
    """
    touch simsapiper_summary.md

    echo "# Input sequences files" >> simsapiper_summary.md
    echo 'No. of sequences in inputfile(s): ' $foundSequencesCount >> simsapiper_summary.md
    echo $inputSeqFiles >> simsapiper_summary.md

    echo '# Data preparation'
    echo "## Data reduction with CD-Hit" >> simsapiper_summary.md
    echo 'Similarity cutoff for CD-Hit: ' $dropSimilar
    echo 'No. of sequences after collapsing: ' $collapsedSequencesCount >> simsapiper_summary.md
    echo 'Find representing and represented sequences here: ' [$similarClstr.baseName]($similarClstr) >> simsapiper_summary.md

    echo '## Invalid sequences ' >> simsapiper_summary.md
    echo 'Sequences removed because they contain more then '$seqQC' % non-standard or unresolved amino acids' >> simsapiper_summary.md
    echo 'Find invalid sequences here: ' [$seqsInvalidFile.baseName]($seqsInvalidFile) >> simsapiper_summary.md

    echo '## Structural information'  >> simsapiper_summary.md
    echo 'Models found in '$structuresFolder' folder at start: '$foundModelsCount >> simsapiper_summary.md
    echo 'Models found in AlphaFold Database: '$foundModelsAF >> simsapiper_summary.md
    echo 'Models generated by ESMF: '$foundModelsESM >> simsapiper_summary.md
    echo 'No. of sequences not matched to a model: ' $structurelessCount  >> simsapiper_summary.md
    echo 'Find sequences not matched to a model here: ' [$structurelessFile.baseName]($structurelessFile) >> simsapiper_summary.md
    
    echo '# Alignment' >> simsapiper_summary.md
    echo '## Generation of subsets' >> simsapiper_summary.md
    #echo 'Subsets were generated from input files:' $useSubsets >> simsapiper_summary.md
    echo 'Subsets were generated with CD-Hit and ' $createSubsets '% sequence similarity cutoff' >> simsapiper_summary.md

    echo 'Find which subset includes which sequence here: ' [$subsetClstr.baseName]($subsetClstr) >> simsapiper_summary.md
    echo '## Align each subsets with T-Coffee' >> simsapiper_summary.md
    echo 'Cleaned, matched sequences to submit to T-coffee: ' [$seqsToAlignFile.baseName]($seqsToAlignFile)  >> simsapiper_summary.md
    echo '## Align subset alignments with MAFFT' >> simsapiper_summary.md
    echo 'Alignment of subset alignments, structureless and orphan sequences ' [$mergedMSA.baseName]($mergedMSA)  >> simsapiper_summary.md

    echo '# Post processing'
    echo '## Squeeze MSA towards conserved secondary structure elements'
    echo 'Cutoff for conserved secondary structure element: ' $squeezePerc >> simsapiper_summary.md
    echo 'DSSP values of each sequences mapped to MSA' [$dsspMappedMSA.baseName]($dsspMappedMSA) >> simsapiper_summary.md
        
    count_file1=\$(grep -o '-' "$mergedMSA" | wc -l)
    count_file2=\$(grep -o '-' "$finalMSA" | wc -l)
    difference=\$((count_file1 - count_file2))
    echo "The inital merged alignment has ' \$count_file1 ' gaps.' >> simsapiper_summary.md
    echo "The the squeezed alignment has ' \$count_file2 ' gaps.' >> simsapiper_summary.md
    echo "The squeezing step removed ' \$difference ' gaps from the alignment.' >> simsapiper_summary.md

    python3  $projectDir/bin/info_msa.py $finalMSA

    """
    //seq id
    //[link](file:///d:/absolute.md)
    //t_coffee -infile msa -evaluate -method sap_pair,TMalign_pair -pdb_dir structures  -output score_pdf,score_ascii
}

process missingQC {
    errorStrategy 'finish'

    input:
    val all 
    val missing
    val strucQC

    output:
    val true, emit: gate

    script:

    """

    result=\$(echo $missing $all | awk '{ print \$1/\$2 }')
    result=\$(echo "\$result" |tr ',' '.')

    result_perc=\$(awk -v res=\$result -v perc=100 'BEGIN{print (res*perc); }')
    result_perc=\$(echo "\$result_perc" |tr ',' '.')

    message="\$result_perc % of sequences not could be matched to a model, please check the structureless_sequences.fasta in the output directory! Try using Colabfold (https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) to provide the missing models!"

    if (( \$(echo "\$result_perc $strucQC" | awk '{ print (\$1 >\$2)}') )); then
        echo "ERROR!"
        echo \$message
        exit 1
    else 
        echo  \$message > structurecheck.txt
    fi

    """
}


process readSeqs {
    publishDir "$params.outFolder/seqs", mode: "copy"
    input:
    val format
    each sequenceFiles

    output:
    path "*.fasta", emit: convertedSeqs


    script:
    """ 
    echo  'converting $sequenceFiles with format $format into ${sequenceFiles.baseName}' 
    python3 $projectDir/bin/convert_to_fasta.py $sequenceFiles $format converted_${sequenceFiles.baseName}
    """
}
